# Generated by Django 3.0.3 on 2020-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_subscriber_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="host",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
