# Generated by Django 3.0.3 on 2020-03-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200227_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='host',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hostmapping',
            name='captured_host',
            field=models.CharField(max_length=255),
        ),
    ]
