# Generated by Django 3.0.7 on 2020-06-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20200612_0038"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backhaulusage",
            old_name="down_kbytes",
            new_name="down_bytes",
        ),
        migrations.RenameField(
            model_name="backhaulusage",
            old_name="up_kbytes",
            new_name="up_bytes",
        ),
        migrations.RenameField(
            model_name="hostusage",
            old_name="down_kbytes",
            new_name="down_bytes",
        ),
        migrations.RenameField(
            model_name="hostusage",
            old_name="up_kbytes",
            new_name="up_bytes",
        ),
        migrations.RenameField(
            model_name="ranusage",
            old_name="down_kbytes",
            new_name="down_bytes",
        ),
        migrations.RenameField(
            model_name="ranusage",
            old_name="up_kbytes",
            new_name="up_bytes",
        ),
        migrations.RenameField(
            model_name="subscriberusage",
            old_name="down_kbytes",
            new_name="down_bytes",
        ),
        migrations.RenameField(
            model_name="subscriberusage",
            old_name="up_kbytes",
            new_name="up_bytes",
        ),
    ]
