# Generated by Django 3.0.7 on 2020-09-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_auto_20200908_2014"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriber",
            old_name="connectivity_status",
            new_name="authorization_status",
        ),
    ]
